from typing import Dict, List


# Common enterprise labels
COMMON_LABELS = [
    "employee",
    "team",
    "department",
    "project",
    "client",
    "vendor",
    "service",
    "application",
    "repository",
    "ticket",
    "incident",
    "meeting",
    "decision",
    "action_item",
    "policy",
    "contract",
    "environment",
    "region",
]

# Source-aware labels
SOURCE_LABELS: Dict[str, List[str]] = {
    "confluence": [
        "service",
        "team",
        "employee",
        "dashboard",
        "slack_channel",
        "deployment_procedure",
        "runbook_action",
        "environment",
        "metric",
        "owner",
        "permission",
        "model",
        "runtime_component",
    ],
    "slack": [
        "person",
        "team",
        "project",
        "model",
        "metric",
        "incident",
        "regression",
        "root_cause",
        "hypothesis",
        "config",
        "calibration_profile",
        "runtime_component",
        "alert",
        "dashboard",
        "action_item",
        "mitigation",
        "ticket",
        "release",
        "timestamp",
    ],
    "gmail": [
        "person",
        "client",
        "project",
        "meeting",
        "contract",
        "invoice",
        "request",
        "approval",
    ],
    "jira": [
        "ticket",
        "incident",
        "task",
        "project",
        "service",
        "priority",
        "environment",
        "assignee",
    ],
    "github": [
        "repository",
        "pull_request",
        "code_review",
        "service",
        "technology",
        "application",
        "release",
    ],
    "linear": [
        "ticket",
        "task",
        "project",
        "milestone",
        "decision",
        "acceptance_criteria",
    ],
    "drive": [
        "document",
        "project",
        "client",
        "contract",
        "policy",
        "presentation",
    ],
    "hubspot": [
        "client",
        "deal",
        "contact",
        "company",
        "pipeline",
        "meeting",
    ],
    "fireflies": [
        "person",
        "meeting",
        "decision",
        "action_item",
        "project",
        "client",
    ],
}
